### PR TITLE
Add lumps of material during deposition

### PR DESCRIPTION
**Pull request by Rombur**
With this PR we can add more materials at once. I choose a deposition time parameter but we can pick something else. I don't know what's easier to use. One thing we need to be careful about is that our source term currently does not support multiple layers at the same time. So if we add too much material at the end of the layer the source term will be wrong.

[CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/390/pipeline)

### CODE REVIEW

**Comment by Rombur** [comment]
DO NOT MERGE: I found a bug.

**Comment by Rombur** [comment]
The CI just started to work again by itself: [CI](https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/adamantine/detail/adamantine/392/pipeline)

**Review by stvdwtt — COMMENTED** [review]
@Rombur Apologies for the late review.

Although the CI passes, if I try to pull this branch and run the SNS Build2 case as-is, I get an error saying that it can't find the mesh. I believe this was fixed by #240.

If I merge master into this branch, that error is gone (as expected). However, the lack of mesh activation bug fixed by #248 crops up again. Since I think you're touching similar code here as there, I wonder if the automatic merge isn't getting it quite right.

That all said, it tested the lumped material addition and it works as expected, which is fantastic.

If you can merge the changes from #248 into this and retain the expected behavior, then I'll approve and merge this in.

**Comment by Rombur** [comment]
Can you try again? I just rebased the branch, it seems to be working fine. When you merged with `master`, was your `master` up-to-date?

**Comment by stvdwtt** [comment]
My master was up to date, but this updated branch is working for me. Maybe your rebase did something different than when I merged?

In any case, this now works for me, so I'm merging it in.

**Pull request merged**
