### PR TITLE
Disable multithreading in Docker image and update README

### PR DESCRIPTION
**Pull request by Rombur**
I was trying to add a new test case but I hit the multithreading bug https://github.com/adamantine-sim/adamantine/issues/130 This PR updates the Docker image and the README

### CODE REVIEW

**Review by stvdwtt — APPROVED** [review]

**Comment by Rombur** [comment]
Retest this please

**Comment by Rombur** [comment]
The reason the failed is due to the fact that we were unlucky in the choice of the random generator and that we converge to the correct solution only for a large sampling size. We use random number in `ensemble_management` and `DataAssimilator`. In `DataAssimilator` the seed is always the same but in `ensemble_management` the seed was different for each run that means that it is impossible to reproduce the result between runs. I have changed that so that the seed is always the same.

**Comment by stvdwtt** [comment]
Ok -- I'm a little leery of always using the same seed (in both cases really, if I was thinking about it I would have used a random seed in DataAssimilator too) for productions runs, but it should be ok for now.

**Comment by Rombur** [comment]
Yes, the numbers will always be the same between run but they will still be random. It's quite common to fix the seed that way if you change a parameter you know that the difference in the output is due to that parameter.

**Pull request merged**
