### PR TITLE
Reduce max FE degree from 10 to 5

### PR DESCRIPTION
**Pull request by Rombur**
I am going to introduce a few more template parameters, so let's reduce the number of instantiations before I do that. This PR also adds the `-ffast-math` flag when compiling the `adamantine` binary in the Docker image.

### CODE REVIEW

**Review by stvdwtt — APPROVED** [review]
Looks good, I'll merge once the CI is done.

**Comment by Rombur** [comment]
I forgot to update `validate_input_database`. I just pushed to fix it.

**Comment by Rombur** [comment]
The CUDA build is not passing but it's due to issue with the CI machines. There is no ETA on when this will be fixed.

**Comment by stvdwtt** [comment]
Merging without the CUDA tests running since we don't know when the CI will be fixed. @Rombur manually ran the tests for HIP and they passed.

**Pull request merged**
