### PR TITLE
Add support for the on-the-fly update of the scan path

### PR DESCRIPTION
**Pull request by Rombur**
@stvdwtt can you try this PR. With it you shouldn't need to restart adamantine to update the scan path.

### CODE REVIEW

**Comment by stvdwtt** [comment]
This works for expected with the scan path: if I swap the scan path file before the simulation gets to the end of the initial scan path file it will load the updated scan path and do the full scan path.

One thing before I approve and merge -- are you intentionally saving recalculation of material addition for a second PR? Because it looks like only the material from the initial scan path gets deposited.

**Comment by Rombur** [comment]
> One thing before I approve and merge -- are you intentionally saving recalculation of material addition for a second PR? Because it looks like only the material from the initial scan path gets deposited.

No,  it's a copy/paste error. Can you remove the `auto` at line 1043 of adamantine.hh and try again

**Comment by Rombur** [comment]
Sorry replace the `auto` by `std::tie(...)`

**Review by stvdwtt — APPROVED** [review]
This has the expected behavior now -- approving and merging.

**Pull request merged**
